<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="EPBYMINW1906" tests="3" failures="2" timestamp="24 Apr 2015 08:24:08 GMT" time="0.02" errors="0">
  <testcase name="COMPARE_BY_DESC_TYPE_Test" time="0.01" classname="ServicesTest"/>
  <testcase name="readAllExceptionTest" time="0.002" classname="ServicesTest">
    <failure type="org.testng.TestException" message="
Expected exception java.lang.IndexOutOfBoundsException but got org.testng.TestException: 
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException">
      <![CDATA[org.testng.TestException: 
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException
	at TestRunner.main(TestRunner.java:21)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Method ServicesTest.readAllExceptionTest() should have thrown an exception of class java.lang.IndexOutOfBoundsException
	... 20 more
... Removed 26 stack frames]]>
    </failure>
  </testcase>
  <testcase name="readAllTest" time="0.0" classname="ServicesTest">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:635)
	at java.util.ArrayList.get(ArrayList.java:411)
	at ServicesTest.readAllTest(ServicesTest.java:21)
	at TestRunner.main(TestRunner.java:21)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
... Removed 26 stack frames]]>
    </failure>
  </testcase>
</testsuite>
