<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="EPBYMINW1906" name="FinderTest" tests="6" failures="0" timestamp="4 May 2015 14:53:56 GMT" time="0.001" errors="0">
  <testcase name="findTours" time="0.000" classname="FinderTest"/>
  <testcase name="findByFoodTest" time="0.000" classname="FinderTest"/>
  <testcase name="findByPriceExceptionTest" time="0.000" classname="FinderTest">
    <error type="com.epam.cdp.byta2015.tourist.exceptions.FindByPriceException" message="[FindByTypeException]: There are not records with price =&#039;777&#039;!">
      <![CDATA[com.epam.cdp.byta2015.tourist.exceptions.FindByPriceException: [FindByTypeException]: There are not records with price ='777'!
	at com.epam.cdp.byta2015.tourist.services.Finder.findByPrice(Finder.java:122)
	at FinderTest.findByPriceExceptionTest(FinderTest.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:673)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:846)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1170)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.runWorkers(TestRunner.java:1147)
	at org.testng.TestRunner.privateRun(TestRunner.java:749)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:317)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:312)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:274)
	at org.testng.SuiteRunner.run(SuiteRunner.java:223)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1039)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:964)
	at org.testng.TestNG.run(TestNG.java:900)
	at TestRunner.main(TestRunner.java:21)
]]>
    </error>
  </testcase>
  <testcase name="findByPriceTest" time="0.000" classname="FinderTest"/>
  <testcase name="findByDescTypeTest" time="0.001" classname="FinderTest"/>
  <testcase name="findByTransportTest" time="0.000" classname="FinderTest"/>
</testsuite>
